"""initial schema (9 tables)

Revision ID: 79bbea48ca69
Revises: 
Create Date: 2026-05-19 10:51:47.318512

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bbea48ca69'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_digest', sa.String(length=255), nullable=False),
    sa.Column('profile_image_url', sa.String(length=1000), nullable=True),
    sa.Column('bio', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exercises_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_table('follows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('following_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> following_id', name=op.f('ck_follows_no_self_follow')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('fk_follows_following_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follows')),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follows_pair')
    )
    op.create_index('idx_follows_follower', 'follows', ['follower_id'], unique=False)
    op.create_index('idx_follows_following', 'follows', ['following_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('metric', sa.String(length=10), nullable=False),
    sa.Column('target_value', sa.Numeric(), nullable=False),
    sa.Column('start_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("metric IN ('sessions', 'volume')", name=op.f('ck_goals_metric_valid')),
    sa.CheckConstraint("period_type IN ('weekly', 'monthly')", name=op.f('ck_goals_period_type_valid')),
    sa.CheckConstraint('target_value > 0', name=op.f('ck_goals_target_value_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals')),
    sa.UniqueConstraint('user_id', 'period_type', name='uq_goals_user_period')
    )
    op.create_table('workouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(length=280), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workouts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts'))
    )
    op.create_index('idx_workouts_user_date', 'workouts', ['user_id', sa.text('performed_on DESC')], unique=False)
    op.create_table('advices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(content) >= 1', name=op.f('ck_advices_content_non_empty')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_advices_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_advices_workout_id_workouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advices'))
    )
    op.create_index('idx_advices_workout', 'advices', ['workout_id', 'created_at'], unique=False)
    op.create_table('cheers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cheers_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_cheers_workout_id_workouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cheers')),
    sa.UniqueConstraint('workout_id', 'user_id', name='uq_cheers_workout_user')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('set_no', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('is_pr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reps >= 1', name=op.f('ck_workout_sets_reps_positive')),
    sa.CheckConstraint('set_no >= 1', name=op.f('ck_workout_sets_set_no_positive')),
    sa.CheckConstraint('weight_kg >= 0', name=op.f('ck_workout_sets_weight_non_negative')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_sets_exercise_id_exercises'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_sets_workout_id_workouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sets'))
    )
    op.create_index('idx_sets_user_exercise', 'workout_sets', ['exercise_id'], unique=False)
    op.create_index('idx_sets_workout', 'workout_sets', ['workout_id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_weight_reps', sa.Integer(), nullable=True),
    sa.Column('max_weight_set_id', sa.BigInteger(), nullable=True),
    sa.Column('max_weight_on', sa.Date(), nullable=True),
    sa.Column('best_volume', sa.Numeric(), nullable=True),
    sa.Column('best_volume_workout_id', sa.BigInteger(), nullable=True),
    sa.Column('best_volume_on', sa.Date(), nullable=True),
    sa.Column('best_est_1rm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('best_1rm_weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('best_1rm_reps', sa.Integer(), nullable=True),
    sa.Column('best_1rm_set_id', sa.BigInteger(), nullable=True),
    sa.Column('best_1rm_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['best_1rm_set_id'], ['workout_sets.id'], name=op.f('fk_personal_records_best_1rm_set_id_workout_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['best_volume_workout_id'], ['workouts.id'], name=op.f('fk_personal_records_best_volume_workout_id_workouts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_personal_records_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['max_weight_set_id'], ['workout_sets.id'], name=op.f('fk_personal_records_max_weight_set_id_workout_sets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_personal_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal_records')),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_pr_user_exercise')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_records')
    op.drop_index('idx_sets_workout', table_name='workout_sets')
    op.drop_index('idx_sets_user_exercise', table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_table('cheers')
    op.drop_index('idx_advices_workout', table_name='advices')
    op.drop_table('advices')
    op.drop_index('idx_workouts_user_date', table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('goals')
    op.drop_index('idx_follows_following', table_name='follows')
    op.drop_index('idx_follows_follower', table_name='follows')
    op.drop_table('follows')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
